name: ccd
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pytorch
  - sentence-transformers
  - idna
  - pytest
  - sentencepiece
  - scikit-learn
  - pip
  - pip:
      - -e .
