#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import tarfile
import tempfile
from pathlib import Path


BLOCKED_NAME_FRAGMENTS = (
    "/private/",
    "__pycache__",
    "anonymization_policy.private",
    "private_mapping",
    ".shuffle_buckets",
)
BLOCKED_SUFFIXES = (".pyc", ".pyo")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def validate_member_name(name: str) -> None:
    normalized = name.replace("\\", "/")
    path = Path(normalized)
    if path.is_absolute() or ".." in path.parts:
        raise ValueError(f"unsafe archive member path: {name}")
    lowered = f"/{normalized.lower()}"
    if any(fragment in lowered for fragment in BLOCKED_NAME_FRAGMENTS):
        raise ValueError(f"blocked private/generated archive member: {name}")
    if lowered.endswith(BLOCKED_SUFFIXES):
        raise ValueError(f"blocked generated bytecode member: {name}")


def validated_regular_members(tar: tarfile.TarFile) -> tuple[list[tarfile.TarInfo], list[str]]:
    members = tar.getmembers()
    names: list[str] = []
    for member in members:
        validate_member_name(member.name)
        if not member.isfile():
            raise ValueError(f"archive member is not a regular file: {member.name}")
        names.append(member.name)
    return members, names


def safe_extract_regular_members(tar: tarfile.TarFile, destination: Path, members: list[tarfile.TarInfo]) -> None:
    root = destination.resolve()
    for member in members:
        target = (destination / member.name).resolve()
        if target != root and root not in target.parents:
            raise ValueError(f"archive member escapes destination: {member.name}")
        target.parent.mkdir(parents=True, exist_ok=True)
        source = tar.extractfile(member)
        if source is None:
            raise ValueError(f"archive member cannot be extracted as a file: {member.name}")
        with source, target.open("wb") as handle:
            shutil.copyfileobj(source, handle)


def extract_validated_bundle(bundle: Path, destination: Path) -> list[str]:
    with tarfile.open(bundle, "r:gz") as tar:
        members, names = validated_regular_members(tar)
        safe_extract_regular_members(tar, destination, members)
    return names


def read_sidecar_digest(sidecar: Path, expected_name: str) -> str:
    parts = sidecar.read_text(encoding="utf-8").strip().split()
    if len(parts) != 2:
        raise ValueError(f"checksum sidecar is not sha256sum-compatible: {sidecar}")
    digest, filename = parts
    if filename != expected_name:
        raise ValueError(f"checksum sidecar filename mismatch in {sidecar}: {filename} != {expected_name}")
    if len(digest) != 64 or any(ch not in "0123456789abcdefABCDEF" for ch in digest):
        raise ValueError(f"checksum sidecar digest is invalid: {sidecar}")
    return digest.lower()


def validate_bundle(bundle: Path, manifest: Path | None = None, bundle_sha256: Path | None = None) -> dict[str, object]:
    bundle = bundle.resolve()
    manifest = manifest.resolve() if manifest else bundle.with_suffix(".manifest.json")
    bundle_sha256 = bundle_sha256.resolve() if bundle_sha256 else bundle.with_suffix(bundle.suffix + ".sha256")

    if not bundle.exists():
        raise FileNotFoundError(bundle)
    if not manifest.exists():
        raise FileNotFoundError(manifest)
    if not bundle_sha256.exists():
        raise FileNotFoundError(bundle_sha256)

    sidecar_digest = read_sidecar_digest(bundle_sha256, bundle.name)
    actual_bundle_digest = sha256(bundle)
    if sidecar_digest != actual_bundle_digest:
        raise ValueError("bundle sha256 sidecar does not match bundle")

    manifest_data = json.loads(manifest.read_text(encoding="utf-8"))
    if manifest_data.get("bundle") != bundle.name:
        raise ValueError("bundle manifest must record only the bundle filename")
    if manifest_data.get("sha256") != actual_bundle_digest:
        raise ValueError("bundle manifest sha256 does not match bundle")
    files = manifest_data.get("files")
    if not isinstance(files, dict) or not files:
        raise ValueError("bundle manifest files map is missing or empty")

    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        with tarfile.open(bundle, "r:gz") as tar:
            members, names = validated_regular_members(tar)
            if sorted(names) != sorted(files):
                raise ValueError("archive members do not match manifest files")
            safe_extract_regular_members(tar, tmp_path, members)

        for name, expected_digest in files.items():
            validate_member_name(name)
            extracted = tmp_path / name
            if not extracted.is_file():
                raise ValueError(f"manifest file not found in extracted bundle: {name}")
            if sha256(extracted) != expected_digest:
                raise ValueError(f"manifest digest mismatch for {name}")

        for sidecar in tmp_path.rglob("*.sha256"):
            target = sidecar.with_name(sidecar.name.removesuffix(".sha256"))
            if target.exists():
                digest = read_sidecar_digest(sidecar, target.name)
                if digest != sha256(target):
                    raise ValueError(f"extracted checksum sidecar does not match target: {sidecar}")

    return {
        "bundle": str(bundle),
        "manifest": str(manifest),
        "sha256_sidecar": str(bundle_sha256),
        "n_files": len(files),
        "status": "pass",
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate a public HIB release bundle and its manifest/checksum sidecars.")
    parser.add_argument("--bundle", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, default=None)
    parser.add_argument("--sha256", type=Path, default=None)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    print(json.dumps(validate_bundle(args.bundle, args.manifest, args.sha256), indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
